export const breads = [
    // Real breads
    "White Bread",
    "Whole Wheat Bread",
    "Sourdough Bread",
    "Rye Bread",
    "Multigrain Bread",
    "Brioche",
    "Baguette",
    "Focaccia",
    "Ciabatta",
    "Pita",
    "Naan",
    "Bagel",
    "English Muffin",
    "Cornbread",
    "Pretzel Roll",
    "Potato Bread",
    "Flatbread",
    "Kaiser Roll",
]

export const sauces = [
    // Classic sauces
    "Mayonnaise",
    "Ketchup",
    "Mustard",
    "Honey Mustard",
    "Barbecue Sauce",
    "Hot Sauce",
    "Ranch",
    "Caesar Dressing",
    "Buffalo Sauce",
    "Thousand Island",
    "Chipotle Mayo",
    "Garlic Aioli",
    "Pesto",
    "Sriracha",
    "Tartar Sauce",
    "Chili Sauce",
    "Sweet Onion Sauce",
    "Vinaigrette",
]

export const meats = [
    // Proteins & Meats
    "Roast Beef",
    "Turkey",
    "Ham",
    "Chicken Breast",
    "Fried Chicken",
    "Grilled Chicken",
    "Tuna",
    "Egg",
    "Boiled Egg",
    "Scrambled Egg",
    "Bacon",
    "Sausage",
    "Meatballs",
    "Pulled Pork",
    "Salami",
    "Pastrami",
    "Chorizo",
    "Steak Strips",
    "Tofu",
    "Tempeh",
    "Falafel",
    "Seitan",
]
export const cheeses = [
    // Cheese Types
    "Cheddar",
    "Swiss",
    "Mozzarella",
    "American Cheese",
    "Provolone",
    "Pepper Jack",
    "Monterey Jack",
    "Brie",
    "Feta",
    "Goat Cheese",
    "Blue Cheese",
    "Parmesan",
    "Cream Cheese",
    "Smoked Gouda",
    "Halloumi",
]

export const veggies = [
    // Veggies & Toppings
    "Lettuce",
    "Tomato",
    "Onion",
    "Red Onion",
    "Pickles",
    "Cucumber",
    "Spinach",
    "Olives",
    "Jalapeños",
    "Bell Peppers",
    "Avocado",
    "Sauerkraut",
    "Coleslaw",
    "Mushrooms",
    "Sun-Dried Tomatoes",
    "Sprouts",
    "Shredded Carrot",
    "Crispy Onions",
    "Corn",
]

export const extras = [
    // Fun & Weird Extras
    "Crushed Chips",
    "French Fries",
    "Mac and Cheese",
    "Pineapple",
    "Peanut Butter",
    "Chocolate Spread",
    "Wasabi Peas",
    "Cereal Crumbs",
    "Slime Jelly",
];

